### ISSUE TITLE
formatting of REQUIRED, OPTIONAL arguments

### ISSUE THREAD

**Issue by JoeZiminski** [neuroinformatics-unit/SWC-BIDS#12]
In the BIDS specification, they format the REQUIRED, OPTIONAL in capitals. Personally I really dont like this, as caps are associated with shouting and in the form "you are REQUIRED to do this", I find it quite irksome. As it is inevitable some people will be annoyed at the proposed changes, I think this styling can make the frustration worse and would suggest using italics for this in our docs. However, this does break with the BIDS docs and maybe I am been too sensitive and no one else minds!

**Comment by adamltyson** [comment]
Any thoughts @niksirbi @lauraporta?

**Comment by niksirbi** [comment]
I'm fine with italics. I think the intention behind the distinct formatting is to signal that these words have a specific meaning here, not a colloquial meaning. Eventually, if we want to be fancy, we could make some formatting rule on the website which automatically renders these keywords in distinct colours (e.g. with traffic light coding), but probably that's an overkill

**Comment by lauraporta** [comment]
I am fine with italics as well. I think they wanted to conform to a defined standard ([RFC2119](https://www.ietf.org/rfc/rfc2119.txt)). I don't think it is that important for us. 
Niko, I like the idea of having custom colors!
