### ISSUE TITLE
Clarify what `imaging` is

### ISSUE THREAD

**Issue by adamltyson** [neuroinformatics-unit/SWC-BIDS#5]
Where we refer to "`imaging` (microscopy)" I would change this to either:
* Allow any kind of imaging (inc fMRI, fUSI etc)
* Specify that it's in-vivo calcium/voltage imaging

It's a bit confusing that we have "`imaging` (microscopy)" and "`histology`" (that's also microscopy).

**Comment by adamltyson** [comment]
> Good question, I think it makes sense to be more specific, for example datatype in bids are subtypes of imaging. Maybe something like for icalc for calcium imaging, ivolt for voltage imaging? We also need something simila for ephys (intracellular vs. extracellular), e.g. ecephys and icphys? 

Here I think we have two options. We could separate everything into calcium imaging, voltage imaging, intrinsic imaging, fUSI etc etc, or just have a functional imaging type that is agnostic to the specific modality. Individual data types could then be like BIDS modalities.

**Comment by niksirbi** [comment]
I would favour Adam's suggestion for now. That means we have a general *functional imaging* data type, which can take several *modalities* as file suffixes (`_calcium`, `_voltage`). We should leave fMRI out of this, if people have fMRI data, they should absolutely follow the normal BIDS standard. I am yet unsure about fUSI, I haven't seen what the data looks like.
In practice, most of the data that goes in this category will be calcium.

**Comment by niksirbi** [comment]
If we wish to constrain imaging to calcium/voltage only, we may call the **optical physiology**/**opto-physiology**. I have heard that term as an analog to electrophysiology. In that case, the data type abbreviation could be `ophys` or `optophys`

**Comment by JoeZiminski** [comment]
This is nice to keep the data type broad and modality more refined, and avoids a lot of overhead with datashuttle. Should the name be something like funcimaging, funcimage, fimaging, invivoimaging, ivimaging?

**Comment by adamltyson** [comment]
Funcimaging is the clearest to me. You could do in vivo structural imaging and that would lead to a different type of analysis.

**Comment by niksirbi** [comment]
I agree with funcimaging, it's the least ambiguous. Btw BIDS uses `func` for fMRI

**Comment by niksirbi** [comment]
If we want to keep everything ultra-short, could also be funcimg
