### ISSUE TITLE
Remove (or finish) incomplete pages

### ISSUE THREAD

**Issue by adamltyson** [neuroinformatics-unit/SWC-BIDS#7]
[This page](https://swc-bids.neuroinformatics.dev/specification.html#the-specification) is unfinished. Considering these pages are accessible externally, I think we should keep unfinished pages as branches until they can be approved via PR, merged and then built.

**Comment by JoeZiminski** [comment]
Because currently the spec is quite short, would it be worth having the landing page as is, and a single other page called something like 'Folder and file naming specification'? It would be nice to have a single page that we could send around.

**Comment by adamltyson** [comment]
Sounds good to me. We can extend the spec with details on separate pages at a later date.
